services:
  postgres:
    image: postgres:16-alpine
    container_name: scanner-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scanner-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scanner-network
    

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - scanner-network

  backend:
    build: .
    container_name: scanner-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/scanner-db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - REDIS_ADDR=redis:6379
    volumes:
      - .:/app
    networks:
      - scanner-network
    depends_on:
      - redis

networks:
  scanner-network:
    external: true

volumes:
  postgres_data:
